### ISSUE TITLE
Login via Spanish SIM refused: "from blocked country 'US'"

### ISSUE THREAD

**Issue by anibtro** [HomeITAdmin/nextcloud_geoblocker#102]
Situation:
My mobile is a dual SIM Android phone with SIM1: German (Vodafone Germany) and SIM2: Spanish (Vodafone Spain).
Nextcloud 24.01 is running on Ubuntu server as snap.
Geoblocker ist set to block all countries except Germany (DE and Spain (ES). Provider is RIRData (local).

Problem:
I'm in Germany at the moment. When SIM1 is activated as data SIM, everything works well. When SIM2 is activated as data SIM, Geoblocker refuses the access to Nextcloud News app, telling the login was from US. Which is untrue, since SIM2 is roaming with Vodafone Germany. But even in Spain it should work, since ES is on the whitelist.
Strange thing is, this only happens with Andoid "Nextcloud News" app. All other apps work well with SIM1 and SIM2.

Thanks in advance for any ideas or help.

**Comment by HomeITAdmin** [comment]
Hi, you must look if the ipv4 or ipv6 block containing your IP can be found in the American file https://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest
If it should be in Germany or Spain it should be in the Europe file https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-latest
If you give me your IP, I can also help with that.

**Comment by anibtro** [comment]
So I activated it again and tested. Again the same behaviour:
When my spanish SIM ist active, the access from Android to my private Nextcloud via apps as well as via Chromium is refused by GeoBlocker, saying it was an attempt from US. I looked into both of your links, but my spanish ipv4 is not in either of them. As soon as I switch to my german SIM everything works as intended.
I updated to the new version that came today, but still the same result.
![1 Spanish IP](https://user-images.githubusercontent.com/67795877/181922378-adb1d3d0-1fd7-49b4-a2cf-fed27fe6cc11.jpg)
![2 Geoblocker-Settings](https://user-images.githubusercontent.com/67795877/181922439-1a1b5f3a-ee2a-4159-bd94-3d7f8590fa93.jpg)
![3 Fehlerprotokoll](https://user-images.githubusercontent.com/67795877/181922487-2a04ba62-4628-4599-8abc-ad34b89cd098.jpg)
![4 Talk-Login](https://user-images.githubusercontent.com/67795877/181922523-5bbeeebe-0cee-43c8-9276-841fd0818e4f.jpg)
![5 Chromium-Login](https://user-images.githubusercontent.com/67795877/181922576-fd906e49-bc96-4ae6-a4de-ce0a81e0e26d.jpg)

**Comment by HomeITAdmin** [comment]
Hi, that is interesting. Looks like RIR data is really wrong here. The ip block that address is part of is assigned to the US since 2012:
`arin|US|ipv4|47.60.0.0|262144|20120515|allocated|63328e60229dd08ae554d530b8d987fd`

Maxmind is assigning this IP to Spain. Looks like they have better information.

So you could switch to Maxmind to solve the issue. 
The app is just an interface to the data provider. Not much that I can do if the data is wrong. :-(

**Comment by anibtro** [comment]
So RIR data appears to be faulty. That's a pity. :-( 
The Maxmind-install-procedure is too complicated for my level of knowledge, as well as the others.
So I'll skip Geoblocker. Thanks anyway for investigating and for your help.
