### ISSUE TITLE
Error "Status of the service cannot be determined."

### ISSUE THREAD

**Issue by vcbranco** [HomeITAdmin/nextcloud_geoblocker#103]
This error is showed at the control panel.
When I run "sudo geoipupdate" there are no errors.
The login attempts are blocked as expected and according to the configuration.
I do not know when the error started.

Debian 11 x86_64
Nextcloud 23.0.7
MaxMind GeoLite2

**Comment by Wotisrv** [comment]
I get the exact same warning.

Fedora Linux 36 (Server Edition)
Nextcloud 24.0.3
MaxMind GeoLite2 4.9.0

**Comment by HomeITAdmin** [comment]
Hi, that is strange.
The error indicates, that the call from the frontend to the backend is not working to show the information. Not sure, what could possibly go wrong here. Here with 23.0.7 it is still working, so it does not seem to be a general issue with newer Nextcloud versions...
Does this error is still there?
Can the status of other localization services be shown?
If you change some configuration below on that page, are they persisted?

**Comment by vcbranco** [comment]
The error at this moment is not the same. Now is "MaxMind GeoLite2": ERROR: Country cannot be found.
The status of the other services is shown.
Changing the configuration including the country allowed return the same error

**Comment by HomeITAdmin** [comment]
Ok, then the first thing i guess was a temporary issue of reaching the backend.

The other one is more clear. The IP I used to check if the service is correctly working apparently does not exist anymore. I change it to another one. I guess quad9 will exist forever. :-)
If the checks run through I will create a bugfix release.

**Comment by vcbranco** [comment]
Geoblocker 0.5.6 installed and working as expected.
Thanks
