### ISSUE TITLE
Wrong Nextcloud configuration (especially in container) can lead to all accesses seem to come from a local network IP address.

### ISSUE THREAD

**Issue by alez007** [HomeITAdmin/nextcloud_geoblocker#105]
Can anyone provide more info about the above ? 

<img width="1399" alt="Screenshot 2022-09-21 at 20 12 15" src="https://user-images.githubusercontent.com/459478/191590542-ce868466-dc52-4ec2-a296-b521c22f8959.png">

**Comment by HomeITAdmin** [comment]
192.168.2.46 looks like a very specific IP in you internal network. I think docker uses other IP ranges for its internal routing by default. 
Are you sure you tested with an external connection? I yes, where is this address used exactly?
How do you configured the trusted_proxies?

**Comment by alez007** [comment]
thanks, I wasn't aware that's the actual IP it's detecting...will keep digging then
