### ISSUE TITLE
Nextcloud crashes caused by exception thrown from geoblocker

### ISSUE THREAD

**Issue by NightFeather** [HomeITAdmin/nextcloud_geoblocker#109]
I'm logging in from ip 100.64.0.1, caused this error, which blocks me from logging into my instance.
`[index] Error: Class "OCA\GeoBlocker\LocalizationServices\GeoBlocker" not found in file '/var/www/html/custom_apps/geoblocker/lib/LocalizationServices/GeoIPLookup.php' line 72`

Nextcloud version: 23.0.11
GeoBlocker version: 0.5.7
GeoBlocker DB version: Maxmind 20191224-3 from debian package

**Comment by HomeITAdmin** [comment]
Hi, Error is in both Services GeoIPLookup and MaxMindGeoLite2. Fix it with the next release. It only happens, when the IP is not found in the database.
