### ISSUE TITLE
Replace app.php with Application.php

### ISSUE THREAD

**Issue by rawtaz** [HomeITAdmin/nextcloud_geoblocker#115]
This app uses a deprecated method of declaring itself, which results in the following log messages:
~~~
Mar 15 11:53:50 DEBUG geoblocker /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.
~~~

Most other apps already use the current method for bootstrapping the app, so there are plenty of examples, but here is the documentation for the proper way to do it: https://docs.nextcloud.com/server/24/developer_manual/app_development/bootstrap.html#the-application-class

**Comment by HomeITAdmin** [comment]
Looks like I missunderstood something here. Does not seem to work correctly. Reverting it for the moment until I really understand how to change it to the new way.
