### ISSUE TITLE
Geoblocker update for Nextcloud 26 ??? 

### ISSUE THREAD

**Issue by Yoanf26** [HomeITAdmin/nextcloud_geoblocker#116]
Is an update planned for Nextcloud 26??

**Comment by HomeITAdmin** [comment]
Hi,
thanks for the hint. Just released a small update. The Unit tests were running fine. Please let me know if you recognize any problems.

**Comment by Yoanf26** [comment]
Hi,

Thanks for the update. I just test with the update and it's ok with Nextcloud 26.

Thank you for your attention and your responsiveness.
