### ISSUE TITLE
RIRData cant finish download

### ISSUE THREAD

**Issue by morka6** [HomeITAdmin/nextcloud_geoblocker#118]
When I want to update the databse (First time) I get an error after a few minutes:

"RIR Data": ERROR: The database is corrupted. Please run update again. Last error message: Not the right number of entries read for IPv4 in region "apnic". Should have been 50390 but was 50389."

I already tried it a few times.
Thanks in advance!

Edit:
GeoBlocker 0.5.8
NC 25.0.5

**Comment by 3por2** [comment]
I also encountered this problem with the exact same error message.

NC 26.01
GeoBlocker 0.5.8

**Comment by HomeITAdmin** [comment]
Hi, is it still occurring? I cannot reproduce it.

**Comment by morka6** [comment]
> Hi, is it still occurring? I cannot reproduce it.

Hey, I just activated the App again and tried to download the database again. Now its working and the app is working as intended. Thanks for your answer! :)
