### ISSUE TITLE
Please add support for NC 29

### ISSUE THREAD

**Issue by Markoise** [HomeITAdmin/nextcloud_geoblocker#128]
It would be wonderful if support for Nextcloud 29 could be added.
Or is it guaranteed that the latest version can be used under NC 29 without any problems?

**Comment by HomeITAdmin** [comment]
Hi nothing is guaranteed of cause ;-)
But unit tests look good so I added 29.
Would be nice if you could check it too.

**Comment by Jonybat** [comment]
Just upgraded from 28.0.5 to 29.0.0 and can confirm it works. It threw an error during the NC upgrade, something like "GeoBlocker not supported, disabled", but it did upgrade the app and it was still enabled.

RIRData upgrade and delay/block capabilities tested working as expected.

Thank you

**Comment by HomeITAdmin** [comment]
Thanks!
