### ISSUE TITLE
Add possibility to block login attempts

### ISSUE THREAD

**Issue by HomeITAdmin** [HomeITAdmin/nextcloud_geoblocker#13]
Add the possibility to block login attempts directly within Nextcloud analogous to brute force app.

**Comment by nsturtz** [comment]
What can I do to help this?

**Comment by HomeITAdmin** [comment]
Hi. My idea was to look at the "Brute-force settings" app, which is blocking IP addresses, when there were to much unsuccessful login attempts. And then to do it in the same way, when an IP address is from a block country and the blocking is activated in the settings. 
Maybe you can outline how the blocking is technically done in the "Brute-force settings" app as a first step.

**Comment by nsturtz** [comment]
Ok, I can take a look at that.

**Comment by nsturtz** [comment]
This is the https://github.com/nextcloud/bruteforcesettings/blob/master/lib/Controller/IPWhitelistController.php
IP Whitelist Controller File

**Comment by HomeITAdmin** [comment]
This doesn't look like the part responsible to block a login attempt from an blocked IP. That is to manage the allow list.

**Comment by szaimen** [comment]
Maybe it would be helpful to ask the developers directly how this the blocking works and can get implemented into this app here:
https://help.nextcloud.com/c/dev/app-dev/
Afaik the developers read this topic and regularly answer questions there.

**Comment by HomeITAdmin** [comment]
Thanks, that is a good idea.
Looking into it I think I found how it is working, but it is good to get a confirmation that this is really the way and cannot be circumvented.

**Comment by HomeITAdmin** [comment]
I implemented it this way, but wait for more answers in the forum before closing.

**Comment by HomeITAdmin** [comment]
No more answers. It seams reasonable this way. Lets get it into testing by the users. 
Maybe it makes sense to add also other blocking possibilities in future versions.
