### ISSUE TITLE
Improving some UI strings

### ISSUE THREAD

**Issue by castillo92** [HomeITAdmin/nextcloud_geoblocker#17]
Hello, I came from Transifex, a site where we translate the app Nextcloud to several locations.

I saw two strings that could be better if we add the words "blacklist and whitelist":

What do you think about adding at the end of this and the other string: "blacklist and whitelist" ?

> No country is blocked but the selected ones **(blacklist)**
> All countries are blocked but the selected ones **(whitelist)**

EDIT: strings can be found here:  (see original string, in english)
https://www.transifex.com/nextcloud/nextcloud/translate/#es/geoblocker/194079957

**Comment by HomeITAdmin** [comment]
I think it is a good idea. I changed the strings. Will go into the next release.
