### ISSUE TITLE
Error GeoBlocker dose not block 

### ISSUE THREAD

**Issue by AndreaXheli** [HomeITAdmin/nextcloud_geoblocker#19]
I've setup the program and checked all my settings but this program only seems to log and dose not block if someone is trying to login from the blocked country i've added to the list. Can you please let me know the issue

**Comment by HomeITAdmin** [comment]
hi
that is easily explained. That is not implemented yet. It is planned for the first major release: #13 

In the moment I am building up the infrastructure to detect the country and wanted to get feedback first from the community, if this is correctly working. And I wanted to learn how to program a Nextcloud app first.

I mention this limitation in the app store, on the settings page and the readme file. Is there another place where you would have expected this information?

**Comment by HomeITAdmin** [comment]
duplicate to #13

**Comment by AndreaXheli** [comment]
Thank you very much for your response! I think this is an amazing idea and id love to see more of this app. Awesome job  if you need anything as far as testing let me know and id be happy to help :)
