### ISSUE TITLE
RIRData: Column not found: 1054 Unknown column '%%%' in 'where clause'

### ISSUE THREAD

**Issue by HomeITAdmin** [HomeITAdmin/nextcloud_geoblocker#31]
There is a error message when trying to find an IP address in the database in some systems but no in all. In my test system it is working fine, but not in the productive system.

**Comment by HomeITAdmin** [comment]
The only obvious difference between the two systems is the database. SQLite vs. MariaDB

**Comment by reiner-text** [comment]
```
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT * FROM `geoblocker_ls_rir` WHERE (`begin_ip_range` <= `626359600`) AND (`is_ip_v6` = `0`) ORDER BY `begin_ip_range` DESC LIMIT 1': SQLSTATE[42S22]: Column not found: 1054 Unknown column '626359600' in 'where clause'
```

Same here with MariaDB. `begin_ip_range` and `is_ip_v6` (numeric) whithout `` works.

**Comment by HomeITAdmin** [comment]
What I am not understanding is I am using the database framework to construct the SQL Statement:
```
$qb = $this->db->getQueryBuilder();

$expr1 = $qb->expr()->lte('begin_ip_range', strval($ip));
$expr2 = $qb->expr()->eq('is_ip_v6', $is_ip_v6);

$qb->select('*')->from($this->getTableName())->where(
  $qb->expr()->andX($expr1, $expr2));

$qb->setMaxResults(1);
$qb->orderBy('begin_ip_range', 'DESC');
```
So the back ticks are not from me, but from the framework. 
On the other hand, such an obvious bug in the framework would have been found long ago, I assume. So it is more likely me, doing something wrong. But I do not see what based on the limited documentation I found so far.
