### ISSUE TITLE
Error log while running

### ISSUE THREAD

**Issue by szaimen** [HomeITAdmin/nextcloud_geoblocker#32]
Hi,

I've just installed this app and now have many of the following error logs inside my logs:

```
[PHP] Error: include(): Failed opening '/var/www/nextcloud/apps/geoblocker/lib/LocalizationServices/../../3rdparty/maxmind_geolite2/geoip2.phar' for inclusion (include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps') at /var/www/nextcloud/apps/geoblocker/lib/LocalizationServices/MaxMindGeoLite2.php#9

GET /settings/**user**/geoblocker
from **ipaddress** by **user** at 2020-07-27T20:49:08+02:00
```

I am actually not sure, if this is a misconfiguration on my side or a bug in the app.
Please tell me.
Thanks!

**Comment by szaimen** [comment]
here is another error log:
[PHP] Error: include(/var/www/nextcloud/apps/geoblocker/lib/LocalizationServices/../../3rdparty/maxmind_geolite2/geoip2.phar): failed to open stream: No such file or directory at /var/www/nextcloud/apps/geoblocker/lib/LocalizationServices/MaxMindGeoLite2.php#9

GET /settings/**user**/geoblocker
from **ipaddress** by **user** at 2020-07-27T20:49:08+02:00

**Comment by HomeITAdmin** [comment]
Thank you for the feedback. This is not a misconfiguration. Not all service must be available, basically it is enough if you have one. The settings side should state the status, that this service is not available. 

It is not a correct behavior of the App, that an error entry reaches the log. I will fix this in the next update.

**Comment by HomeITAdmin** [comment]
Duplicate to #30
