### ISSUE TITLE
Make app available on Nextcloud 20

### ISSUE THREAD

**Issue by HomeITAdmin** [HomeITAdmin/nextcloud_geoblocker#36]
Test if it is working as expected. If not fix it.

**Comment by nsturtz** [comment]
ok

**Comment by HomeITAdmin** [comment]
@nsturtz: "ok" means, you will look into it or you looked into it and everything was working ok with Nextcloud 20. ;-)

**Comment by sunjam** [comment]
Working fine for me on NextcloudPi 20.0.0

Thanks for working on this.

**Comment by nsturtz** [comment]
> @nsturtz: "ok" means, you will look into it or you looked into it and everything was working ok with Nextcloud 20. ;-)

I have looked into it and no issues at all for me.

**Comment by HomeITAdmin** [comment]
Thanks for the help. Added support for Nextcloud 20.

**Comment by szaimen** [comment]
@HomeITAdmin Thank you for adding the support for NC20, would it be possible to release a new version to the store so that anybody can use it with NC20 without having to click on the button: enable untested version? Thanks in advance!

**Comment by HomeITAdmin** [comment]
I moved some stuff to a later version and released that one. I think it is a good package for 0.4.0 and it is released now.
Thanks for the hint that people are waiting for the NC20 support.
