### ISSUE TITLE
"MaxMind GeoLite2": ERROR: Service does not seem to be installed correctly or database is not available at /usr/share/GeoIP/GeoLite2-Country.mmdb.

### ISSUE THREAD

**Issue by vcbranco** [HomeITAdmin/nextcloud_geoblocker#43]
- The location of the database is correct.
- The database date is shown
- Don't have any error when I run run "sudo geoipupdate"
- After configure the country permited I test with a country bloqued IP address and I don't have any entry on the Nextcloud log and       the error is shown in the configuration page

**Comment by vcbranco** [comment]
Found this error in the log

[PHP] Error: Error: filemtime(): stat failed for /var/lib/GeoIP/GeoLite2-Country.mmdb at /var/www/nextcloud/apps/geoblocker/lib/LocalizationServices/MaxMindGeoLite2.php#87 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "filemtime(): st ... b", "/var/www/nextcl ... p", 87, [])
 1. /var/www/nextcloud/apps/geoblocker/lib/LocalizationServices/MaxMindGeoLite2.php line 87
    filemtime("/var/lib/GeoIP/GeoLite2-Country.mmdb")
 2. /var/www/nextcloud/apps/geoblocker/lib/Controller/ServiceController.php line 45
    OCA\GeoBlocker\LocalizationServices\MaxMindGeoLite2->getDatabaseDate()
 3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\GeoBlocker\Controller\ServiceController->getDatabaseDate(1)
 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\GeoBlocker\C ... {}, "getDatabaseDate")
 5. /var/www/nextcloud/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\GeoBlocker\C ... {}, "getDatabaseDate")
 6. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\GeoBlocker ... r", "getDatabaseDate", OC\AppFramework\ ... {}, {id: "1",_route: ... "})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({id: "1",_route: ... "})
 8. /var/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {id: "1",_route: ... "})
 9. /var/www/nextcloud/lib/base.php line 1011
    OC\Route\Router->match("/apps/geoblocke ... 1")
10. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /apps/geoblocker/service/getDatabaseDate/1
from 192.168.1.23 by sysadmin at 2020-11-03T22:30:14+00:00

**Comment by vcbranco** [comment]
Another error:

[geoblocker] Warning: The login of user "sysadmin" with IP address "82.102.16.197" could not be checked due to problems with location service.

POST /login
from 82.102.16.197 at 2020-11-03T23:34:05+00:00

**Comment by HomeITAdmin** [comment]
Ok, the long error message is happening, because it is trying to check the date of the file "/var/lib/GeoIP/GeoLite2-Country.mmdb", but your database is on "/usr/share/GeoIP/GeoLite2-Country.mmdb". I guess this entry happened during the configuration, when the path was still on default before you could change it to your path. That is not nice that in that case an error appears in the log. This I should be able to fix easily.

But this does not explain you problem. The other waring in the log is wanted when the service is not ok, then the warning should tell the administrator that a login could not be verified. 
Because the date of the db is shown correctly, the database is not my first guess for the source of the problem. 
Just to double check because you do not mentioned it explicitly, you installed the "geoip2.phar" to the folder "3rdparty/maxmind_geolite2/" below the geoblocker app folder?

**Comment by vcbranco** [comment]
I changed for my path.
First time I configured the path was not changed, only in the second time I tryed. Maybe that is the reason it is in the log.
I did not find any other reference to that.

The geoip2.phar file is in the folder.

**Comment by HomeITAdmin** [comment]
While checking I found another not so nice behavior: #44. But this can also not be your problem, then you would have a different behavior.

Can you double check that the web server have read access to the database file.

Do you use a Debian based distribution? Or which one are you using?
I do not know how it is for other distributions, but for Debian (Buster) based ones the default directory for the ".mmdb" files from "sudo geoipupdate" should be "/var/lib/GeoIP". Under "/usr/share/GeoIP" there are only the ".dat" files from Geoiplookup by default (I just see that I mentioned the wrong directory in the readme, I will correct this). Is this different on your system or do you copy the file manually to that directory?

**Comment by vcbranco** [comment]
Corrected the path and file location to /var/lib/GeoIP/ - same behavior

I'm runing Debian 10 x86_64 Intel NUC with Nextcloudpi curl installation

I think the permitions are correct:       -rw-r--r-- 1 root root 3934555 Nov  7 00:32 /var/lib/GeoIP/GeoLite2-Country.mmdb      -rw-r--r-- 1 root root 366335 Oct  1 19:48 /var/www/nextcloud/3rdparty/maxmind_geolite2/geoip2.phar

I copied the file manually to /var/lib/GeoIP/

The two path are present in my system  /var/lib/GeoIP   and   /usr/share/GeoIP
It was not necessary to create any folder

**Comment by vcbranco** [comment]
Maybe a permissions problem

From my user (non root) I can read /usr/share/GeoIP but I have permission denied for /var/www/nextcloud/3rdparty/maxmind_geolite2/

Maybe is happening the same for www-data, but the file was already on  /usr/share/GeoIP where I can read as a normal user

**Comment by HomeITAdmin** [comment]
I think there is the problem. The geoip2.phar file must go into the apps 3party folder. So given your installation path it should be under "/var/www/nextcloud/custom_apps/geoblocker/3rdparty/maxmind_geolite2/". The folder should already exist.

**Comment by vcbranco** [comment]
Now I found the correct path but is not that, is:
/var/www/nextcloud/apps/geoblocker/3rdparty/maxmind_geolite2/

I moved the file there and is working well

Better correct the readme with the full path because /var/www/nextcloud/3rdparty exists and peolple like me can make that mistake.
Many thanks.

**Comment by squintarelli** [comment]
I am having the same issue... (CentOS)
"MaxMind GeoLite2": ERROR: Service does not seem to be installed correctly or database is not available at /var/lib/GeoIP/GeoLite2-Country.mmdb.

geoipupdate run smoothly; 
I edited /etc/GeoIP.conf to change the path to point to /usr/local/share/GeoIP/
but didn't work.
geoip2.phar is present in /var/www/cloud.quintarelli.it/web/apps/geoblocker/3rdparty/maxmind_geolite2
GeoLite2-Country.mmdb is present in /usr/local/share/GeoIP/
all directories are -rw-r--r-- 

any ideas ?

**Comment by HomeITAdmin** [comment]
I do not see any typo in the path but just to be sure, use copy-paste so that the configuration is correct.

Can you change permission to 666 for the geoip2.phar and the database that you are using for a test, to varify that it is definitely not a permission issue.

**Comment by squintarelli** [comment]
thx. 
I copied-pasted
changed all permissions to geoip2.phar and GeoLite2-Country.mmdb to 666.

even tried in nextcloud settings interface to set the location of the DB to
/usr/share/GeoIP/GeoLite2-Country.mmdb
/usr/share/GeoIP/
/usr/share/GeoIP
(just in case)

but still not working..
:-(

is there some service I have to restart or something ?

**Comment by HomeITAdmin** [comment]
No, I do not know of anything that would need restart. 

You can try the following. Open a shell and go to the folder of the geoip2.phar. Then start an interactive php shell:
`sudo -u www-data php -a` 
(Replace www-data with the user of the web server in CentOS)

Then try to run this line of code (replacing the db path for your system, and run it as one line in the shell):
`include 'geoip2.phar'; use GeoIp2\Database\Reader; $reader = new Reader('/var/lib/GeoIP/GeoLite2-Country.mmdb'); print($reader->country('24.165.23.67')->country->isoCode);`

It should print out "US". If not, it hopefully prints out some helpful error messages.

Besides that test at some point of the debugging I start blaming SELinux or AppArmor. Are you using one of these?

**Comment by squintarelli** [comment]
first of all, thanks..
selinux is disabled and am not runing apparmor.

when I run the command as 'apache' user, it nicely return US. 
but my nextcloud instance's user is web1.
when I run the command as 'web1' user, it returns this error:

PHP Warning:  Uncaught InvalidArgumentException: The file "/usr/share/GeoIP/GeoLite2-Country.mmdb" does not exist or is not readable. in phar:///var/www/clients/client0/web1/web/apps/geoblocker/3rdparty/maxmind_geolite2/geoip2.phar/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php:83
Stack trace:
#0 phar:///var/www/clients/client0/web1/web/apps/geoblocker/3rdparty/maxmind_geolite2/geoip2.phar/src/Database/Reader.ph/tp(56): MaxMind\Db\Reader->__construct('/usr/share/GeoI...')
#1 php shell code(1): GeoIp2\Database\Reader->__construct('/usr/share/GeoI...')
#2 {main}
  thrown in phar:///var/www/clients/client0/web1/web/apps/geoblocker/3rdparty/maxmind_geolite2/geoip2.phar/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php on line 83
 
the file "/usr/share/GeoIP/GeoLite2-Country.mmdb" is there and permissions are 666

I hope this helps..

**Comment by HomeITAdmin** [comment]
For some reason the user "web1" does not have access to the file "/usr/share/GeoIP/GeoLite2-Country.mmdb" .
If it is not permission, and not SELinux and not AppArmor then I am out of ideas.
If you try to open the file as "web1" user, do you also get the permission denied?

You could try to put the db file in the same folder as "geoip2.phar". Maybe that works.

**Comment by squintarelli** [comment]
yes, it's odd..


>If you try to open the file as "web1" user, do you also get the permission denied?

I'm not sure I understand.. which file do you mean ? the geoip2.phar opened as web1 gives the error in my previous comment. If you mean the  GeoLite2-Country.mmdb, how should I try to open it ?

**Comment by squintarelli** [comment]
> You could try to put the db file in the same folder as "geoip2.phar". Maybe that works.

guess what ?
it worked!

thanks for all the help, man..

**Comment by HomeITAdmin** [comment]
I meant something like
`sudo -u web1 more /usr/share/GeoIP/GeoLite2-Country.mmdb`

Ok, this way it is at least working. It is of course not so nice, that you have to copy an updated database always to that place. It still feels like there must be something else in CentOS preventing the user web1 to access the other folder. Maybe a CentOS Forum can help there.

**Comment by squintarelli** [comment]
I will.. I'll turn to this thread to posst a reply if I get any.

I set in both, nextcloud Geoip settings and /etc/Geoip.conf, the following
/var/www/clients/client0/web1/web/apps/geoblocker/3rdparty/maxmind_geolite2/
as the DB directory

I then run geoipupdate and got no error. 
I'd hope the updates put the DB in the right directory...

how frequently is the DB updated ? (so I can turn and check if it worked ok ?

**Comment by HomeITAdmin** [comment]
That I do not know, how often they update. You could delete the db in that folder and run the update. I everything works fine, it should be created again.

**Comment by squintarelli** [comment]
it updates nicely. :-)

**Comment by flavienbwk** [comment]
For those looking for the `geoip2.phar`, it can be found on [maxmind/GeoIP2-php's release page](https://github.com/maxmind/GeoIP2-php/releases). For the `GeoLite2-Country.mmdb` file, go to https://github.com/P3TERX/GeoLite.mmdb.

**Comment by versussoft** [comment]
Actually you can put GeoLite2-Country.mmdb in /var/lib/GeoIP
But must set /var/lib/GeoIP in the PHP open_basedir configuration of the web host
