### ISSUE TITLE
Menu entry is missing in 0.4.0 

### ISSUE THREAD

**Issue by Stef-33560** [HomeITAdmin/nextcloud_geoblocker#46]
Hi,

Wheter I set the language to "French" or I set the language to "French" and the locale to "English", the menu "GeoBlocker" is missing from the admin page.

The only solution is to set language to "English" as the locale (language AND locale).

I did not notice any issue about this, sorry if this is a well known error.

Stef

**Comment by HomeITAdmin** [comment]
Hi Stef,

I have trouble to reproduce this behavior, on all my systems I can switch from and to french and the admin settings page stays the whole time (I just do not understand anything anymore ;-) ).

Can you add some more information, like what Nextcloud version you are using, which other apps have you installed, do you have log entries? 
Can you switch back and force between the languages and then the settings appear and disappear, or is the app deactivated when the settings are gone?

Maybe it also helps to deactivate the app, erase it and install it again.

Best

**Comment by Stef-33560** [comment]
Oh dear, I understood ....

I was looking for "GeoBlocker" entry... 
but in French, the translation is "Bloqueur géographique" **and not** GeoBlocker !
