### ISSUE TITLE
Unable to install RIR-Database

### ISSUE THREAD

**Issue by lightlike** [HomeITAdmin/nextcloud_geoblocker#47]
## Versions

Nextcloud: 19.0.4 (Linuxserver.io Docker)
GeoBlocker: 0.4.0

## Issue

Unable to install RIR-Database

Says: "Update available" (translated)

## Error

Web:
```
Database is corrupted. Please update. (tranlated)
Last error: Problem during erasing the whole database occured.
```

DB-Repair (OCC):
```
There was a problem when reseting the database. Reset function returned false.
```

## More Information

- Already had geoblocker installed some time ago and removed app while Database-Update was running (maybe not the best idea)
- `allow_url_fopen` is set

**Comment by HomeITAdmin** [comment]
Hmm, this looks strange. I would have expected, that the reset using the cli would always work, because it just calls the Nextcloud interface to erase all entries in the relevant table. 

Which database type are you using?
Do you have full access to the database and can check, if this table is existing "%PRÄFIX%_geoblocker_ls_rir" in the database?

A shot into the dark would be just calling "maintenance:repair" using the cli. Not sure what it is doing exactly, but the documentation is saying something about "clean up the database". Maybe that helps. Of course it is not restricted to this app, so it may have an effect on the whole installation. A backup before that should be mandatory.

**Comment by lightlike** [comment]
Database: MariaDB (Linuxserver.io Docker)

I have full access. The geoblocker table does not exist in my DB. But that might have been because I was fed up with some other stuff on my server and just deleted that one.
It seems that I dopped the table before I started making regular backups. Is there a ready to use create command anywhere? Maybe that will work.

I alredy executed maintenance:repair before I wrote this issue. Did not work.

**Comment by HomeITAdmin** [comment]
I think there are two options to get the database back:
1. 
- remove the app completely
- manually remove the "geoblocker" entries in the %präfix%_appconfig table. 
- Installing the app again should bring everything back. 
2. 
- maybe just calling the migration directly helps. Maybe one of the two commands is working:
  - migrations:migrate geoblocker 
  - migrations:execute geoblocker 000300Date20200413202844
- it would also be interesting to see the result before from the command:
  - migration:status geoblocker

**Comment by HomeITAdmin** [comment]
A third option could be to manually set the version of the app in the %präfix%_appconfig table to 0.2.0. Then nextcloud should offer to update the app again and do the whole migration again and create the table again..

**Comment by HomeITAdmin** [comment]
I think the best order is to try option 2 first. If this is not working option 3 and then option 1.

**Comment by lightlike** [comment]
Option 2:

Status:
```
    >> App:                                                geoblocker
    >> Version Table Name:                                 oc_migrations
    >> Migrations Namespace:                               OCA\GeoBlocker\Migration
    >> Migrations Directory:                               /config/www/nextcloud/apps/geoblocker/lib/Migration
    >> Previous Version:                                   0
    >> Current Version:                                    000300Date20200413202844
    >> Next Version:                                       Already at latest migration step
    >> Latest Version:                                     000300Date20200413202844
    >> Executed Migrations:                                1
    >> Executed Unavailable Migrations:                    1
    >> Available Migrations:                               1
    >> New Migrations:                                     1
    >> Pending Migrations:                                 None
```

Migrate: nothing    no table in DB
Migrate (specific):
```
Can not go back to previous migration without debug enabled
```

Option 3:
Did Web-Repair after version set, but no luck.

Option 1:
Also no luck. Same error as before.


I did get a fopen() timeout error in logging when I tried to recreate the table myself though.

**Comment by HomeITAdmin** [comment]
I checked it on my test system and it worked with "migrations:execute geoblocker 000300Date20200413202844" when I set debug to true in the config file. The table is recreated then.

**Comment by lightlike** [comment]
That worked. Thanks a lot. 😄
