### ISSUE TITLE
geoip2.phar file deleted by the Nextcloud upgrade from 19.0.5 to 20.0.2

### ISSUE THREAD

**Issue by vcbranco** [HomeITAdmin/nextcloud_geoblocker#48]
The file was deleted by the upgrade and the Geoblocker stopped working.
It was necessary to download and copy the file manually to its location. After that the Geoblocker started to work again.

**Comment by HomeITAdmin** [comment]
Thanks for the feedback. I have to look into that.
First guess would be, that Nextcloud is deleting the app during update and installing it again. This would explain that every additional file is gone. In that case we would have to find a better place for the geoip2.phar file.

**Comment by vcbranco** [comment]
That's what I thought

**Comment by vcbranco** [comment]
Only to confirm.
It happened again in the upgrade from 20.0.2 to 20.0.3.

**Comment by HomeITAdmin** [comment]
How are updating your Nextcloud instance?

**Comment by vcbranco** [comment]
I'm using [Nextcloudpi](https://ownyourbits.com/nextcloudpi/) on Debian 10 x86_64 curl instalation.
The updates/upgrades are maid by the Nextcloudpi updater and not by the Nextcloud updater

**Comment by HomeITAdmin** [comment]
You can now put the "geoip2.phar" file alternatively in the same folder as the database.
