### ISSUE TITLE
Multiple lines with geoiplookup

### ISSUE THREAD

**Issue by cool18m** [HomeITAdmin/nextcloud_geoblocker#57]
my geoiplookup outputs more lines than you have implementet in your code, if i disable these extra lines your code works without a problem.
it would be nice, if we can also use these information to block
geoiplookup 8.8.8.8
GeoIP Country Edition: US, United States
GeoIP City Edition, Rev 1: US, 00, N/A, N/A, N/A, 37.750999, -97.821999, 0, 0
GeoIP ASNum Edition: AS15169 GOOGLE

**Comment by HomeITAdmin** [comment]
Ok, I didn't know that this is possible. How do you get it to output more lines?

**Comment by cool18m** [comment]
I'm on archlinux and installed the package geoip-database-extra

**Comment by HomeITAdmin** [comment]
The commit should fix, that it is ignoring other lines. 
Can you test this by exchanging the "lib/LocalizationServices/GeoIPLookup.php" with the latest version in the repository?

Can you also give me the output of `geoiplookup -v 0.0.0.0` on your system with all lines enabled?

**Comment by cool18m** [comment]
Yes seems to work now!

```
geoiplookup -v 0.0.0.0
GeoIP Country Edition: GeoLite2 Country 20210223
GeoIP City Edition, Rev 1: GeoLite2 City 20210223
GeoIP ASNum Edition:
GeoIP Country V6 Edition: GeoLite2 Country 20210223
GeoIP ASNum V6 Edition:
GeoIP City Edition V6, Rev 1: GeoLite2 City 20210223
```

**Comment by HomeITAdmin** [comment]
So with the latest fix showing the date on the settings page should also work. If you can confirm this I would close this ticket and make another one for the request to use the additional information. At the moment the whole app is only for blocking based on countries. I am not sure if and when I will come to this.
