### ISSUE TITLE
Allowing only one IP not country

### ISSUE THREAD

**Issue by hw-p** [HomeITAdmin/nextcloud_geoblocker#66]
is it possible ?

**Comment by HomeITAdmin** [comment]
Possible is a lot ;-)

To be honest I am not sure if it fits. I am a big fan of "do one thing well". 
And the one thing is being an interface to geolocalization services and not an ipblocker.
On the other hand you could define your request as a special case of the more general use case, that you want to define the mapping of IP addresses to countries by yourself (in your case one IP is mapped to one country and the rest is unknown). That could be a valid use case although stretching it a little bit. Maybe this is also helpful in a testing use case.

Are there more opinions out there or more people needing this?

**Comment by vcbranco** [comment]
"Do one thing well" is a great thing.
IP bloking is a diferent app and in the Nextcloud store there are an app to allow only the IP's we want (I know, not the same thing).
Maybe IP bloking make more sense in that app.

https://apps.nextcloud.com/apps/limit_login_to_ip

Just my opinion.

**Comment by HomeITAdmin** [comment]
If I understand it correctly, the "Restrict login to IP addresses" app is exactly, what @hw-p is looking for.
So perfect solution from my point of view: Instant solution for hw-p and we can keep the focus of the geoblocker app. 
So I will close the issue, but if someone disagrees please do not hesitate to keep the discussion open.
