### ISSUE TITLE
Bug in RIRData with IPv6

### ISSUE THREAD

**Issue by HomeITAdmin** [HomeITAdmin/nextcloud_geoblocker#69]
From questions #68 :
Device 1:
The user \"NOT_SHOWN_IN_LOG\" attempt to login with IP address \"2a03:567:....\" from blocked country \"CZ\".
Device 2:
{... The user \"NOT_SHOWN_IN_LOG\" attempt to login with IP address \"2a02:8070:........." from blocked country \"AA\".

I checked them against de RIR Data from your link. The result should be "DE", I think.
Device 1: ripencc | DE | ipv6 |2a03:560:: | 29| 20140701| allocated
Device 2: ripencc | DE | ipv6 |2a02:8070:: | 31| 20110913| allocated

**Comment by HomeITAdmin** [comment]
@mike842 : I have trouble to reproduce the problem. On my test system I always get the correct answer "DE" for several IP addresses I tested with these two prefixes.
Can you double check that have the latest release (0.4.6) and make another successful DB update with that version?

**Comment by HomeITAdmin** [comment]
@mike842: Another idea if the problem still extists, can you also print the output of the php line on the machine running you run Nextcloud on:
`php -r 'echo PHP_INT_MIN . "\n";'`

**Comment by mike842** [comment]
> Can you double check that have the latest release (0.4.6) and make another successful DB update with that version?

yes of course. I'm on the latest release (0.4.6)  and I had updated my DB, so the DB was an the newest version. 
To reproduce it the bug again, I updated the DB again (Date of DB is now: 2021-05-01), Geoblocker release is (0.4.6). 

So, at them moment I'm not at home, so my Login-Device IP-Adress has changed. 
Now I get another Country, but I'm still blocked: 
`,"message":"The user \"****\" attempt to login with IP address \"2001:16b8:........\" from blocked country \"PL\". Login is blocked by exception."`

> @mike842: Another idea if the problem still extists, can you also print the output of the php line on the machine you are running Nextcloud on:
> `php -r 'echo PHP_INT_MIN . "\n";'`

yes of course, the output of this is: 
php -r 'echo PHP_INT_MIN . "\n";'
`-2147483648
`

**Comment by HomeITAdmin** [comment]
Ok, then I know at least the root cause. I forgot that for IPv6 the current implementation needs a 64bit system and you have a 32 bit system.
So the admin should be at least correctly informed, that this is not working. I am also checking, if I could make it also possible on 32 bit systems.

**Comment by mike842** [comment]
> Ok, then I know at least the root cause. I forgot that for IPv6 the current implementation needs a 64bit system and you have a 32 bit system.
> So the admin should be at least correctly informed, that this is not working. I am also checking, if I could make it also possible on 32 bit systems without to much effort.

Thank you very much for figuring that out! For me, the GeoIpLookup is working. ;) 
Thanks and best regards.

**Comment by HomeITAdmin** [comment]
I added statements on less then 64 bit systems, that this will not work with IPv6. IPv6 will then always return "Country not found" and the admin can decide what to do in that case.
