### ISSUE TITLE
Clicking on Geoblocker option from Settings will add underlines to all other listed options

### ISSUE THREAD

**Issue by elhananjair** [HomeITAdmin/nextcloud_geoblocker#70]
Hello there, simple issue I guess, When I click on Geoblocker from Settings other listed options of setting will turned into some kind of link, underline will be added to others. 
![Capture](https://user-images.githubusercontent.com/69236638/116841886-36c8fe80-abe3-11eb-80cb-c198addc5561.PNG)

**Comment by HomeITAdmin** [comment]
Is already solved in #64.
Will be in the next release.

**Comment by HomeITAdmin** [comment]
Duplicate to #64
