### ISSUE TITLE
RIR DB won't populate

### ISSUE THREAD

**Issue by cyberpower678** [HomeITAdmin/nextcloud_geoblocker#88]
I'm getting this error when trying to update the DB.

[PHP] Error: Undefined array key "COUNT(*)" at /var/www/html/apps/geoblocker/lib/Db/RIRServiceMapper.php#85

GET /index.php/apps/geoblocker/service/getAllServiceData/2
from 192.168.1.1 by ncadmin at 2021-11-07T21:47:01+00:00

**Comment by HomeITAdmin** [comment]
This is a duplicate to: https://github.com/HomeITAdmin/nextcloud_geoblocker/issues/86
I hope that I have next week time to make a release to distribute the solution.
