### ISSUE TITLE
Preference for allowlist is not saved

### ISSUE THREAD

**Issue by EWouters** [HomeITAdmin/nextcloud_geoblocker#89]
When I try to edit the setting for "Choose the selection mode" and set it to "All countries are blocked but the selected ones (allowlist)" it does not save the setting and when I reload the page it is back to the blocklist setting.

**Comment by HomeITAdmin** [comment]
Hi,

my first guess is, that you block javascript?

If not, what OS and Browser are you using? Can you also try with another Browser?

**Comment by EWouters** [comment]
Yes, it seems my ad blockers were stopping me from editing that specific setting. I tried Safari with AdBlock Plus and Firefox 94 with uBlock Origin on MacOS. Both blocked me from editing the setting, disabling AdBlock Plus solved it for me. Thank you.
