### ISSUE TITLE
GeoBlocker App update with OCC?

### ISSUE THREAD

**Issue by nextcloudfan** [HomeITAdmin/nextcloud_geoblocker#93]
I use the Geoblocker app with the RIR Data service to download the IPs.

Is there any way to do the update with the OCC command and set up a system cronjob if needed?

Thanks

**Comment by HomeITAdmin** [comment]
That is not possible yet, but I think it is a good idea.

There was already the idea in #29 to have a possibility within Nextcloud. I guess there are use cases for both, but just a command is probably easier to provide and enough for a lot of admins. So makes sense to add this.

**Comment by nextcloudfan** [comment]
Do you have plans for the release date of 0.5.5. already?

**Comment by HomeITAdmin** [comment]
No, at the moment not, sorry. I have a lot of private and business commitments at the moment that leave only very little time for my hobbies. :-(

**Comment by nextcloudfan** [comment]
Can you please provide the command ton run:)?

**Comment by HomeITAdmin** [comment]
As for all commands you get them, when you run `sudo -u %NEXTCLOUD_INSTANCE_USER% php occ`, also the ones for Geoblocker:
```
 geoblocker
  geoblocker:country-selection:reset              Resets the country selection, so that no country is blocked.
  geoblocker:localization-service:list-services   List the IDs of the localization services.
  geoblocker:localization-service:reset-db        Reset the database for the given localization service.
  geoblocker:localization-service:select-service  Select the location service, that is used to determine the country code.
  geoblocker:localization-service:update-db       Update the database for the given localization service.
```

Using a command with `--help` you get the details:
```
Description:  
    Update the database for the given localization service. 
Usage: 
    geoblocker:localization-service:update-db [<service_id>]
Arguments: 
    service_id            The ID of the localization service, whose database will be updated. If not given the current service will be used.
```
