### ISSUE TITLE
"GeoIp2\Database\Reader" does not exist

### ISSUE THREAD

**Issue by gpgmailencrypt** [HomeITAdmin/nextcloud_geoblocker#94]
Suddenly my logs get be flooded with
```
[geoblocker] Error: Geoblocker: MaxMindGeoLite2: Database Reader is not available: "GeoIp2\Database\Reader" does not exists.
```
I'm not quite sure, what this error means. Is it a problem on the geolite2 database side (other programs work fine with my maxmind installation) or is it a problem of the nextcloud geoblocker (version 0.5.2 on nextcloud 22.2.3)?
Reinstalling the app didn't help.

Thanks in advance

**Comment by HomeITAdmin** [comment]
Hi,

Was the Geoblocker App with MaxMind working before and then suddenly the log entries came?

Are the installation steps fullfilled from the readme?: 
"Download the file "geoip2.phar" to the folder "3rdparty/maxmind_geolite2/" inside the GeoBlocker app folder (the folder already exists under "$NEXTCLOUD_ROOT$/$CUSTOM_APP_FOLDER$/geoblocker/3rdparty/maxmind_geolite2/") from the MaxMind GeoIP2 release page. Alternatively you can put the file in the same folder as the database mentioned below (from version 0.4.5 on)."

**Comment by gpgmailencrypt** [comment]
the geoblocker app was installed before and worked like a charm. The error happened after the last update. You were right, the geoip2.phar was indeed missing. It seems it was deleted during the last update. But now it works again Thanks

**Comment by HomeITAdmin** [comment]
Ok, there was a similar case in issue #48, but there it was the update of the whole Nextcloud instance. The "solution" was to use the option to put the geoip2.phar file in the same place as the database. The chances to survive an update should be higher there.
