### ISSUE TITLE
integrity check failed on extra files

### ISSUE THREAD

**Issue by seventer** [HomeITAdmin/nextcloud_geoblocker#96]
Running NC 21.0.9 I get an integrity failed on extra files. Does anyone know how to correct this?

In my case the files are:

`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- geoblocker
	- EXTRA_FILE
		- 3rdparty/rir_data/afrinic.txt
		- 3rdparty/rir_data/lacnic.txt
		- 3rdparty/rir_data/ripencc.txt
		- 3rdparty/rir_data/arin.txt
		- 3rdparty/rir_data/apnic.txt

Raw output
==========
Array
(
    [geoblocker] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [3rdparty/rir_data/afrinic.txt] => Array
                        (
                            [expected] => 
                            [current] => ab5d84948910502946607f1b294e605cb7e1c3290356b33041fb08491275c65a7fc74a3347f51d1835944ff3e52497c302366776063ecdc131a8f0e500e58e51
                        )

                    [3rdparty/rir_data/lacnic.txt] => Array
                        (
                            [expected] => 
                            [current] => 5ba233d5ece15c9beac69a2589fc82317e1538323aead9b6c565ab1d814f81db78711aa6fddbc48150e8d74eca58a13f010156c02140234de8d71bc82209f367
                        )

                    [3rdparty/rir_data/ripencc.txt] => Array
                        (
                            [expected] => 
                            [current] => 13a8326a8c751b010f54012d1738a68ae22a98b842510dda5a78ebed3535aaf5f044ab73a7fc868c051b6d791bb758dac83b691a9faca8eb333e826070b8eb69
                        )

                    [3rdparty/rir_data/arin.txt] => Array
                        (
                            [expected] => 
                            [current] => 603f9010b54dc7aa3514cdb3153e3e5a872347ddb835a314bd03e8f16e8860827920f456cb313c7c6ea4cde78787769bf7200799851bbf3f34e8b1411d225a3e
                        )

                    [3rdparty/rir_data/apnic.txt] => Array
                        (
                            [expected] => 
                            [current] => 23b0e22369090e0ae4c28c82326771699ba37204cef424a5b7235dbf382fe25c96fc6d053ca71b213523c525ba2b720f77983e0c3eb92252987c29e9c5a17594
                        )

                )

        )

)`

**Comment by lxto** [comment]
I'm facing the same issue after updating from NV 23.0.0 to 23.0.2

**Comment by HomeITAdmin** [comment]
ok, the reason is probably that I changed the release process. I used this to also add code signing and this was probably not a good idea, because during the update process I create the above mentioned files, which are then not signed. 

Very short solution you can erase these files. 
I have to think about what the best long term solution is. For the moment it is probably the best to remove the code singing again, that not more are running into the same problem.

**Comment by HomeITAdmin** [comment]
Please let me know if it is ok with 0.5.4 again.

**Comment by seventer** [comment]
Thanks for the update! With 0.5.4 the "check failed" is gone.

**Comment by flatterrich** [comment]
here, too, the "check failed" is gone with 0.5.4.
